//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyClinic.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Translator {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translator() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyClinic.Resources.Translator", typeof(Translator).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Diagnosis.
        /// </summary>
        public static string AddDiagnosis {
            get {
                return ResourceManager.GetString("AddDiagnosis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Disease.
        /// </summary>
        public static string AddDisease {
            get {
                return ResourceManager.GetString("AddDisease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Employee.
        /// </summary>
        public static string AddEmployee {
            get {
                return ResourceManager.GetString("AddEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Medicine.
        /// </summary>
        public static string AddMedicine {
            get {
                return ResourceManager.GetString("AddMedicine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Patient.
        /// </summary>
        public static string AddPatient {
            get {
                return ResourceManager.GetString("AddPatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Prescription.
        /// </summary>
        public static string AddPrescription {
            get {
                return ResourceManager.GetString("AddPrescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add User.
        /// </summary>
        public static string AddUser {
            get {
                return ResourceManager.GetString("AddUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjustment Report.
        /// </summary>
        public static string AdjustmentReport {
            get {
                return ResourceManager.GetString("AdjustmentReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age.
        /// </summary>
        public static string Age {
            get {
                return ResourceManager.GetString("Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to edit this.
        /// </summary>
        public static string AreSureEditPresc {
            get {
                return ResourceManager.GetString("AreSureEditPresc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to remove this.
        /// </summary>
        public static string AreSureRemovePresc {
            get {
                return ResourceManager.GetString("AreSureRemovePresc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audit Log Report.
        /// </summary>
        public static string AuditLogReport {
            get {
                return ResourceManager.GetString("AuditLogReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back To List.
        /// </summary>
        public static string BackToList {
            get {
                return ResourceManager.GetString("BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup.
        /// </summary>
        public static string Backup {
            get {
                return ResourceManager.GetString("Backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup For.
        /// </summary>
        public static string BackupFor {
            get {
                return ResourceManager.GetString("BackupFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup Management.
        /// </summary>
        public static string BackupManagement {
            get {
                return ResourceManager.GetString("BackupManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string CategoryId {
            get {
                return ResourceManager.GetString("CategoryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Name.
        /// </summary>
        public static string CategoryName {
            get {
                return ResourceManager.GetString("CategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed.
        /// </summary>
        public static string Closed {
            get {
                return ResourceManager.GetString("Closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Logo.
        /// </summary>
        public static string CompanyLogo {
            get {
                return ResourceManager.GetString("CompanyLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comparison.
        /// </summary>
        public static string Comparison {
            get {
                return ResourceManager.GetString("Comparison", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to clear all medicine?.
        /// </summary>
        public static string ConfirmClearPrescription {
            get {
                return ResourceManager.GetString("ConfirmClearPrescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract Date.
        /// </summary>
        public static string ContractDate {
            get {
                return ResourceManager.GetString("ContractDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract Date is not valid.
        /// </summary>
        public static string ContractDateIsNotValid {
            get {
                return ResourceManager.GetString("ContractDateIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created By.
        /// </summary>
        public static string CreatedBy {
            get {
                return ResourceManager.GetString("CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created By Id.
        /// </summary>
        public static string CreatedById {
            get {
                return ResourceManager.GetString("CreatedById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created Date.
        /// </summary>
        public static string CreatedDate {
            get {
                return ResourceManager.GetString("CreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSV.
        /// </summary>
        public static string Csv {
            get {
                return ResourceManager.GetString("Csv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Month.
        /// </summary>
        public static string CurrentMonth {
            get {
                return ResourceManager.GetString("CurrentMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily Cash-flow Report.
        /// </summary>
        public static string DailyCashFlowReport {
            get {
                return ResourceManager.GetString("DailyCashFlowReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily Operation Report.
        /// </summary>
        public static string DailyOperationReport {
            get {
                return ResourceManager.GetString("DailyOperationReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Of Birth.
        /// </summary>
        public static string DateOfBirth {
            get {
                return ResourceManager.GetString("DateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        public static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dayend Close.
        /// </summary>
        public static string DayendClose {
            get {
                return ResourceManager.GetString("DayendClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dayend Close Report.
        /// </summary>
        public static string DayendCloseReport {
            get {
                return ResourceManager.GetString("DayendCloseReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dayend Close Summary.
        /// </summary>
        public static string DayendCloseSummary {
            get {
                return ResourceManager.GetString("DayendCloseSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dayend Close Summary Report.
        /// </summary>
        public static string DayendCloseSummaryReport {
            get {
                return ResourceManager.GetString("DayendCloseSummaryReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dayend Close Transaction Report.
        /// </summary>
        public static string DayendCloseTransactionReport {
            get {
                return ResourceManager.GetString("DayendCloseTransactionReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dayend Closing For.
        /// </summary>
        public static string DayendClosingFor {
            get {
                return ResourceManager.GetString("DayendClosingFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days.
        /// </summary>
        public static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        public static string Detail {
            get {
                return ResourceManager.GetString("Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail All.
        /// </summary>
        public static string DetailAll {
            get {
                return ResourceManager.GetString("DetailAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prescription Detail.
        /// </summary>
        public static string DetailPrescription {
            get {
                return ResourceManager.GetString("DetailPrescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail User.
        /// </summary>
        public static string DetailUser {
            get {
                return ResourceManager.GetString("DetailUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnose By.
        /// </summary>
        public static string DiagnoseBy {
            get {
                return ResourceManager.GetString("DiagnoseBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diag.Cycle.
        /// </summary>
        public static string DiagnoseCycle {
            get {
                return ResourceManager.GetString("DiagnoseCycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnose Date.
        /// </summary>
        public static string DiagnoseDate {
            get {
                return ResourceManager.GetString("DiagnoseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnosis.
        /// </summary>
        public static string Diagnosis {
            get {
                return ResourceManager.GetString("Diagnosis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnosis.
        /// </summary>
        public static string DiagnosisDescription {
            get {
                return ResourceManager.GetString("DiagnosisDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnosis​ Detail.
        /// </summary>
        public static string DiagnosisDetail {
            get {
                return ResourceManager.GetString("DiagnosisDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnosis Management.
        /// </summary>
        public static string DiagnosisManagement {
            get {
                return ResourceManager.GetString("DiagnosisManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnosis Photo.
        /// </summary>
        public static string DiagnosisPhoto {
            get {
                return ResourceManager.GetString("DiagnosisPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disease.
        /// </summary>
        public static string Disease {
            get {
                return ResourceManager.GetString("Disease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disease Detail.
        /// </summary>
        public static string DiseaseDetail {
            get {
                return ResourceManager.GetString("DiseaseDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disease Management.
        /// </summary>
        public static string DiseaseManagement {
            get {
                return ResourceManager.GetString("DiseaseManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disease Name.
        /// </summary>
        public static string DiseaseName {
            get {
                return ResourceManager.GetString("DiseaseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disease Summary Report.
        /// </summary>
        public static string DiseaseSummaryReport {
            get {
                return ResourceManager.GetString("DiseaseSummaryReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctor Name.
        /// </summary>
        public static string DoctorName {
            get {
                return ResourceManager.GetString("DoctorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctor Report.
        /// </summary>
        public static string DoctorOperationReport {
            get {
                return ResourceManager.GetString("DoctorOperationReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctor Tel.
        /// </summary>
        public static string DoctorTel {
            get {
                return ResourceManager.GetString("DoctorTel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you wish to Rollback the dayend close of.
        /// </summary>
        public static string DoYouWishToRollbackTheDayendCloseOf {
            get {
                return ResourceManager.GetString("DoYouWishToRollbackTheDayendCloseOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you wish to run the dayend close of.
        /// </summary>
        public static string DoYouWishToRunTheDayendCloseOf {
            get {
                return ResourceManager.GetString("DoYouWishToRunTheDayendCloseOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Diagnosis.
        /// </summary>
        public static string EditDiagnosis {
            get {
                return ResourceManager.GetString("EditDiagnosis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Disease.
        /// </summary>
        public static string EditDisease {
            get {
                return ResourceManager.GetString("EditDisease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Employee.
        /// </summary>
        public static string EditEmployee {
            get {
                return ResourceManager.GetString("EditEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Medicine.
        /// </summary>
        public static string EditMedical {
            get {
                return ResourceManager.GetString("EditMedical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Medicine.
        /// </summary>
        public static string EditMedicine {
            get {
                return ResourceManager.GetString("EditMedicine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Patient.
        /// </summary>
        public static string EditPatient {
            get {
                return ResourceManager.GetString("EditPatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Prescription.
        /// </summary>
        public static string EditPrescription {
            get {
                return ResourceManager.GetString("EditPrescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit User.
        /// </summary>
        public static string EditUser {
            get {
                return ResourceManager.GetString("EditUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is not valid. (ex : example@gmail.com).
        /// </summary>
        public static string EmailIsNotValid {
            get {
                return ResourceManager.GetString("EmailIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee.
        /// </summary>
        public static string Employee {
            get {
                return ResourceManager.GetString("Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Detail.
        /// </summary>
        public static string EmployeeDetail {
            get {
                return ResourceManager.GetString("EmployeeDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Management.
        /// </summary>
        public static string EmployeeManagement {
            get {
                return ResourceManager.GetString("EmployeeManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Not Found..
        /// </summary>
        public static string Error404 {
            get {
                return ResourceManager.GetString("Error404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have authorized to access this page ..
        /// </summary>
        public static string ErrorNonAuthorized {
            get {
                return ResourceManager.GetString("ErrorNonAuthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your session has timed out. please login again..
        /// </summary>
        public static string ErrorSession {
            get {
                return ResourceManager.GetString("ErrorSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expired.
        /// </summary>
        public static string Expired {
            get {
                return ResourceManager.GetString("Expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Visit Date.
        /// </summary>
        public static string ExpireDate {
            get {
                return ResourceManager.GetString("ExpireDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expired Item.
        /// </summary>
        public static string ExpiredItem {
            get {
                return ResourceManager.GetString("ExpiredItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expired Item Summary Report.
        /// </summary>
        public static string ExpiredItemSummaryReport {
            get {
                return ResourceManager.GetString("ExpiredItemSummaryReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expire.
        /// </summary>
        public static string ExpiredStatus {
            get {
                return ResourceManager.GetString("ExpiredStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expire Item.
        /// </summary>
        public static string ExpireItem {
            get {
                return ResourceManager.GetString("ExpireItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure Dayend Close.
        /// </summary>
        public static string FailureDayendClose {
            get {
                return ResourceManager.GetString("FailureDayendClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter :.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First.
        /// </summary>
        public static string First {
            get {
                return ResourceManager.GetString("First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Date.
        /// </summary>
        public static string FromDate {
            get {
                return ResourceManager.GetString("FromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green.
        /// </summary>
        public static string Green {
            get {
                return ResourceManager.GetString("Green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive.
        /// </summary>
        public static string Inactive {
            get {
                return ResourceManager.GetString("Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index.
        /// </summary>
        public static string Index {
            get {
                return ResourceManager.GetString("Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inflow.
        /// </summary>
        public static string Inflow {
            get {
                return ResourceManager.GetString("Inflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsActived.
        /// </summary>
        public static string IsActived {
            get {
                return ResourceManager.GetString("IsActived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsLocked.
        /// </summary>
        public static string IsLocked {
            get {
                return ResourceManager.GetString("IsLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Special.
        /// </summary>
        public static string IsSpecial {
            get {
                return ResourceManager.GetString("IsSpecial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last.
        /// </summary>
        public static string Last {
            get {
                return ResourceManager.GetString("Last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Date.
        /// </summary>
        public static string LogDate {
            get {
                return ResourceManager.GetString("LogDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logged in as.
        /// </summary>
        public static string Loggedinas {
            get {
                return ResourceManager.GetString("Loggedinas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Management.
        /// </summary>
        public static string LogManagement {
            get {
                return ResourceManager.GetString("LogManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Page.
        /// </summary>
        public static string LogPage {
            get {
                return ResourceManager.GetString("LogPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Made By.
        /// </summary>
        public static string MadeBy {
            get {
                return ResourceManager.GetString("MadeBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medicine.
        /// </summary>
        public static string Medicine {
            get {
                return ResourceManager.GetString("Medicine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medicine Detail.
        /// </summary>
        public static string MedicineDetail {
            get {
                return ResourceManager.GetString("MedicineDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medicine Management.
        /// </summary>
        public static string MedicineManagement {
            get {
                return ResourceManager.GetString("MedicineManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medicine Name.
        /// </summary>
        public static string MedicineName {
            get {
                return ResourceManager.GetString("MedicineName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medicine Type.
        /// </summary>
        public static string MedicineType {
            get {
                return ResourceManager.GetString("MedicineType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input your value for form before you click on.
        /// </summary>
        public static string MessageForm {
            get {
                return ResourceManager.GetString("MessageForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The bold of title is required..
        /// </summary>
        public static string MessageForm1 {
            get {
                return ResourceManager.GetString("MessageForm1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to below button.
        /// </summary>
        public static string MessageFormBold {
            get {
                return ResourceManager.GetString("MessageFormBold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info..
        /// </summary>
        public static string MessageInfo {
            get {
                return ResourceManager.GetString("MessageInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can not edit this pawn because is expired to edit..
        /// </summary>
        public static string MessageNonAlthorize {
            get {
                return ResourceManager.GetString("MessageNonAlthorize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can not reprint, please contact supperuser or administrator.
        /// </summary>
        public static string MessageNotRePrint {
            get {
                return ResourceManager.GetString("MessageNotRePrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The system will save your data auto when lost focus from controller..
        /// </summary>
        public static string MessageSetting {
            get {
                return ResourceManager.GetString("MessageSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified By.
        /// </summary>
        public static string ModifiedBy {
            get {
                return ResourceManager.GetString("ModifiedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified Date.
        /// </summary>
        public static string ModifiedDate {
            get {
                return ResourceManager.GetString("ModifiedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        public static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly.
        /// </summary>
        public static string Monthly {
            get {
                return ResourceManager.GetString("Monthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly Comparation Operation.
        /// </summary>
        public static string MonthlyComparationOperation {
            get {
                return ResourceManager.GetString("MonthlyComparationOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly Comparation Operation Report.
        /// </summary>
        public static string MonthlyComparationOperationReport {
            get {
                return ResourceManager.GetString("MonthlyComparationOperationReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly Operation Report.
        /// </summary>
        public static string MonthlyOperationReport {
            get {
                return ResourceManager.GetString("MonthlyOperationReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mor.
        /// </summary>
        public static string Mor {
            get {
                return ResourceManager.GetString("Mor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to more than.
        /// </summary>
        public static string MoreThan {
            get {
                return ResourceManager.GetString("MoreThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Morning.
        /// </summary>
        public static string Morning {
            get {
                return ResourceManager.GetString("Morning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you wish to backup record of.
        /// </summary>
        public static string MsgBackup {
            get {
                return ResourceManager.GetString("MsgBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string MsgClose {
            get {
                return ResourceManager.GetString("MsgClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete record number.
        /// </summary>
        public static string MsgConfirmDelete {
            get {
                return ResourceManager.GetString("MsgConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you wish to delete diagnosis have patient name.
        /// </summary>
        public static string MsgConfirmDeleteDiagnosis {
            get {
                return ResourceManager.GetString("MsgConfirmDeleteDiagnosis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you wish to delete disease name.
        /// </summary>
        public static string MsgConfirmDeleteDisease {
            get {
                return ResourceManager.GetString("MsgConfirmDeleteDisease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you wish to delete employee name.
        /// </summary>
        public static string MsgConfirmDeleteEmployee {
            get {
                return ResourceManager.GetString("MsgConfirmDeleteEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you wish to delete medicine name.
        /// </summary>
        public static string MsgConfirmDeleteMedicine {
            get {
                return ResourceManager.GetString("MsgConfirmDeleteMedicine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you wish to delete patient name.
        /// </summary>
        public static string MsgConfirmDeletePatient {
            get {
                return ResourceManager.GetString("MsgConfirmDeletePatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you wish to delete perscription have patient name .
        /// </summary>
        public static string MsgConfirmDeletePerscription {
            get {
                return ResourceManager.GetString("MsgConfirmDeletePerscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete user name.
        /// </summary>
        public static string MsgConfirmDeleteUser {
            get {
                return ResourceManager.GetString("MsgConfirmDeleteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you wish to delete this image ?.
        /// </summary>
        public static string MsgDeleteImage {
            get {
                return ResourceManager.GetString("MsgDeleteImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnosis . .
        /// </summary>
        public static string MsgDiagnosis {
            get {
                return ResourceManager.GetString("MsgDiagnosis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Can&apos;t be Delete, because it was used by.
        /// </summary>
        public static string MsgFailureDelete {
            get {
                return ResourceManager.GetString("MsgFailureDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Diagnose Name Invalid, please select again..
        /// </summary>
        public static string MsgInvalidDiagnoseName {
            get {
                return ResourceManager.GetString("MsgInvalidDiagnoseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Disease Name Invalid, please select again..
        /// </summary>
        public static string MsgInvalidDiseaseName {
            get {
                return ResourceManager.GetString("MsgInvalidDiseaseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Patient Name Invalid, please select again..
        /// </summary>
        public static string MsgInvalidPatientName {
            get {
                return ResourceManager.GetString("MsgInvalidPatientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item ..
        /// </summary>
        public static string MsgItem {
            get {
                return ResourceManager.GetString("MsgItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prescription ..
        /// </summary>
        public static string MsgPrescription {
            get {
                return ResourceManager.GetString("MsgPrescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record have been deleted ..
        /// </summary>
        public static string MsgSuccessDelete {
            get {
                return ResourceManager.GetString("MsgSuccessDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Testing.
        /// </summary>
        public static string MyTesting {
            get {
                return ResourceManager.GetString("MyTesting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nation.
        /// </summary>
        public static string N_Nation {
            get {
                return ResourceManager.GetString("N_Nation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name can&apos;t be empty.
        /// </summary>
        public static string NameEmpty {
            get {
                return ResourceManager.GetString("NameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nation.
        /// </summary>
        public static string Nation {
            get {
                return ResourceManager.GetString("Nation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string NewStatus {
            get {
                return ResourceManager.GetString("NewStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Night.
        /// </summary>
        public static string Night {
            get {
                return ResourceManager.GetString("Night", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noon.
        /// </summary>
        public static string Noon {
            get {
                return ResourceManager.GetString("Noon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        public static string Normal {
            get {
                return ResourceManager.GetString("Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Allow Print.
        /// </summary>
        public static string NotAllowPrint {
            get {
                return ResourceManager.GetString("NotAllowPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Found.
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One Day Remain ..
        /// </summary>
        public static string OneDayRemain {
            get {
                return ResourceManager.GetString("OneDayRemain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation.
        /// </summary>
        public static string Operation {
            get {
                return ResourceManager.GetString("Operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outflow.
        /// </summary>
        public static string Outflow {
            get {
                return ResourceManager.GetString("Outflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string PatentName {
            get {
                return ResourceManager.GetString("PatentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient.
        /// </summary>
        public static string Patient {
            get {
                return ResourceManager.GetString("Patient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient Detail.
        /// </summary>
        public static string PatientDetail {
            get {
                return ResourceManager.GetString("PatientDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient History.
        /// </summary>
        public static string PatientHistory {
            get {
                return ResourceManager.GetString("PatientHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient Managerment.
        /// </summary>
        public static string PatientManagerment {
            get {
                return ResourceManager.GetString("PatientManagerment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient Name.
        /// </summary>
        public static string PatientName {
            get {
                return ResourceManager.GetString("PatientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient Operation Report.
        /// </summary>
        public static string PatientOperationReport {
            get {
                return ResourceManager.GetString("PatientOperationReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone can&apos;t be empty.
        /// </summary>
        public static string PhoneEmpty {
            get {
                return ResourceManager.GetString("PhoneEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input your value..
        /// </summary>
        public static string Pleaseinputyourvalue {
            get {
                return ResourceManager.GetString("Pleaseinputyourvalue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input your value before you click on button add.
        /// </summary>
        public static string Pleaseinputyourvalueforformbeforeyouclickonbuttonadd {
            get {
                return ResourceManager.GetString("Pleaseinputyourvalueforformbeforeyouclickonbuttonadd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Police Report .
        /// </summary>
        public static string PoliceReport {
            get {
                return ResourceManager.GetString("PoliceReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prescription Management.
        /// </summary>
        public static string PrescriptionManagement {
            get {
                return ResourceManager.GetString("PrescriptionManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Month.
        /// </summary>
        public static string PreviousMonth {
            get {
                return ResourceManager.GetString("PreviousMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        public static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print History.
        /// </summary>
        public static string PrintHistory {
            get {
                return ResourceManager.GetString("PrintHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Prescription.
        /// </summary>
        public static string PrintPrescription {
            get {
                return ResourceManager.GetString("PrintPrescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Type.
        /// </summary>
        public static string ProcessType {
            get {
                return ResourceManager.GetString("ProcessType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qty.
        /// </summary>
        public static string Qty {
            get {
                return ResourceManager.GetString("Qty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason.
        /// </summary>
        public static string Reason {
            get {
                return ResourceManager.GetString("Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string RecordNo {
            get {
                return ResourceManager.GetString("RecordNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Records.
        /// </summary>
        public static string Records {
            get {
                return ResourceManager.GetString("Records", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red.
        /// </summary>
        public static string Red {
            get {
                return ResourceManager.GetString("Red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remark.
        /// </summary>
        public static string Remark {
            get {
                return ResourceManager.GetString("Remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember.
        /// </summary>
        public static string Remember {
            get {
                return ResourceManager.GetString("Remember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renew.
        /// </summary>
        public static string Renew {
            get {
                return ResourceManager.GetString("Renew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report.
        /// </summary>
        public static string Report {
            get {
                return ResourceManager.GetString("Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string Reports {
            get {
                return ResourceManager.GetString("Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string ResetController {
            get {
                return ResourceManager.GetString("ResetController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        public static string Result {
            get {
                return ResourceManager.GetString("Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return To Home.
        /// </summary>
        public static string ReturnToHome {
            get {
                return ResourceManager.GetString("ReturnToHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rollback.
        /// </summary>
        public static string Rollback {
            get {
                return ResourceManager.GetString("Rollback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run.
        /// </summary>
        public static string Run {
            get {
                return ResourceManager.GetString("Run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run Again.
        /// </summary>
        public static string RunAgain {
            get {
                return ResourceManager.GetString("RunAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search For.
        /// </summary>
        public static string SearchFor {
            get {
                return ResourceManager.GetString("SearchFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --- Select Category ---.
        /// </summary>
        public static string SelectCategory {
            get {
                return ResourceManager.GetString("SelectCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Doctor.
        /// </summary>
        public static string SelectDoctor {
            get {
                return ResourceManager.GetString("SelectDoctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SelectOne.
        /// </summary>
        public static string SelectOne {
            get {
                return ResourceManager.GetString("SelectOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Process Type.
        /// </summary>
        public static string SelectProcessType {
            get {
                return ResourceManager.GetString("SelectProcessType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Status.
        /// </summary>
        public static string SelectStatus {
            get {
                return ResourceManager.GetString("SelectStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select User.
        /// </summary>
        public static string SelectUser {
            get {
                return ResourceManager.GetString("SelectUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting.
        /// </summary>
        public static string Setting {
            get {
                return ResourceManager.GetString("Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Severity.
        /// </summary>
        public static string Severity {
            get {
                return ResourceManager.GetString("Severity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sex.
        /// </summary>
        public static string Sex {
            get {
                return ResourceManager.GetString("Sex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skill.
        /// </summary>
        public static string Skill {
            get {
                return ResourceManager.GetString("Skill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special.
        /// </summary>
        public static string Special {
            get {
                return ResourceManager.GetString("Special", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status Type.
        /// </summary>
        public static string StatusType {
            get {
                return ResourceManager.GetString("StatusType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Total.
        /// </summary>
        public static string SubTotal {
            get {
                return ResourceManager.GetString("SubTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success Dayend Close.
        /// </summary>
        public static string SuccessDayendClose {
            get {
                return ResourceManager.GetString("SuccessDayendClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symptom.
        /// </summary>
        public static string Symptom {
            get {
                return ResourceManager.GetString("Symptom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symptom Type.
        /// </summary>
        public static string SymptomType {
            get {
                return ResourceManager.GetString("SymptomType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID Type.
        /// </summary>
        public static string T_Type {
            get {
                return ResourceManager.GetString("T_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tel.
        /// </summary>
        public static string Tel {
            get {
                return ResourceManager.GetString("Tel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tel1.
        /// </summary>
        public static string Tel1 {
            get {
                return ResourceManager.GetString("Tel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tel2.
        /// </summary>
        public static string Tel2 {
            get {
                return ResourceManager.GetString("Tel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tel3.
        /// </summary>
        public static string Tel3 {
            get {
                return ResourceManager.GetString("Tel3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Diagnosis.
        /// </summary>
        public static string ThisDiagnosis {
            get {
                return ResourceManager.GetString("ThisDiagnosis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Disease.
        /// </summary>
        public static string ThisDisease {
            get {
                return ResourceManager.GetString("ThisDisease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Doctor.
        /// </summary>
        public static string ThisEmployee {
            get {
                return ResourceManager.GetString("ThisEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Medicine.
        /// </summary>
        public static string ThisMedicine {
            get {
                return ResourceManager.GetString("ThisMedicine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Patient.
        /// </summary>
        public static string ThisPatient {
            get {
                return ResourceManager.GetString("ThisPatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Date.
        /// </summary>
        public static string ToDate {
            get {
                return ResourceManager.GetString("ToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today Backup on.
        /// </summary>
        public static string TodayBackupon {
            get {
                return ResourceManager.GetString("TodayBackupon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total All Dianosis.
        /// </summary>
        public static string TotalAllDianosis {
            get {
                return ResourceManager.GetString("TotalAllDianosis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Day Allow Print.
        /// </summary>
        public static string TotalDayAllowPrint {
            get {
                return ResourceManager.GetString("TotalDayAllowPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Diagnosis.
        /// </summary>
        public static string TotalDiagnosis {
            get {
                return ResourceManager.GetString("TotalDiagnosis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Date.
        /// </summary>
        public static string TransactionDate {
            get {
                return ResourceManager.GetString("TransactionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TransDate.
        /// </summary>
        public static string TransDate {
            get {
                return ResourceManager.GetString("TransDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trans Description.
        /// </summary>
        public static string TransDescription {
            get {
                return ResourceManager.GetString("TransDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two Day Remain ..
        /// </summary>
        public static string TwoDayRemain {
            get {
                return ResourceManager.GetString("TwoDayRemain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string U_Name {
            get {
                return ResourceManager.GetString("U_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected Error.
        /// </summary>
        public static string UnexpectedError {
            get {
                return ResourceManager.GetString("UnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        public static string UnitId {
            get {
                return ResourceManager.GetString("UnitId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload....
        /// </summary>
        public static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Management.
        /// </summary>
        public static string UploadManagement {
            get {
                return ResourceManager.GetString("UploadManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage.
        /// </summary>
        public static string Usage {
            get {
                return ResourceManager.GetString("Usage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage.
        /// </summary>
        public static string UsageId {
            get {
                return ResourceManager.GetString("UsageId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use.
        /// </summary>
        public static string Use {
            get {
                return ResourceManager.GetString("Use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Id.
        /// </summary>
        public static string UserId {
            get {
                return ResourceManager.GetString("UserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Management.
        /// </summary>
        public static string UserManagement {
            get {
                return ResourceManager.GetString("UserManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Managerment.
        /// </summary>
        public static string UserManagerment {
            get {
                return ResourceManager.GetString("UserManagerment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name can&apos;t be empty.
        /// </summary>
        public static string UserNameEmpty {
            get {
                return ResourceManager.GetString("UserNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Page.
        /// </summary>
        public static string UserPage {
            get {
                return ResourceManager.GetString("UserPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Type.
        /// </summary>
        public static string UserType {
            get {
                return ResourceManager.GetString("UserType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit Date.
        /// </summary>
        public static string Visit {
            get {
                return ResourceManager.GetString("Visit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Visit Date.
        /// </summary>
        public static string VisitAgain {
            get {
                return ResourceManager.GetString("VisitAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting....
        /// </summary>
        public static string Waiting {
            get {
                return ResourceManager.GetString("Waiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yellow.
        /// </summary>
        public static string Yellow {
            get {
                return ResourceManager.GetString("Yellow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
